### PR TITLE
Modified README.md to include the Compass extension

### PR DESCRIPTION
**Pull request by stephenway**
Some Compass users prefer to use a compass extension for a framework, so I made one. If you don't mind I'd like to have it listed in the readme so the users know it's an option.

### CODE REVIEW

**Comment by therg** [comment]
Thanks for this, coming from Compass and being accustomed to Compass extensions, it's odd Helium wasn't packaged that way.

**Comment by cbrauckmuller** [comment]
I am pretty new to authoring in Sass and Compass, so to be honest, I didn't even know this was an option. I am looking into making this part of the master.

**Comment by stephenway** [comment]
@cbrauckmuller :+1: Would you mind me helping you with that?

**Comment by cbrauckmuller** [comment]
Definitely would like the help. I don't have much time to work on it right now but will take a look this week.

**Pull request closed without merging**
